FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV BACKEND_HOST=0.0.0.0
ENV BACKEND_PORT=8787

COPY backend ./backend
COPY package.json package-lock.json ./

EXPOSE 8787

CMD ["node", "./backend/src/server.mjs"]
