(function attachDuvelaAppI18n(global) {
  'use strict';

  const FALLBACK_LOCALES = [
    { code: 'en', name: 'English', flag: '🇬🇧', dir: 'ltr' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
    { code: 'es', name: 'Español', flag: '🇪🇸', dir: 'ltr' },
    { code: 'fr', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
    { code: 'it', name: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
    { code: 'pt', name: 'Português', flag: '🇵🇹', dir: 'ltr' },
    { code: 'nl', name: 'Nederlands', flag: '🇳🇱', dir: 'ltr' },
    { code: 'sv', name: 'Svenska', flag: '🇸🇪', dir: 'ltr' },
    { code: 'no', name: 'Norsk', flag: '🇳🇴', dir: 'ltr' },
    { code: 'pl', name: 'Polski', flag: '🇵🇱', dir: 'ltr' },
    { code: 'cs', name: 'Čeština', flag: '🇨🇿', dir: 'ltr' },
    { code: 'sq', name: 'Shqip', flag: '🇦🇱', dir: 'ltr' },
    { code: 'tr', name: 'Türkçe', flag: '🇹🇷', dir: 'ltr' },
    { code: 'ru', name: 'Русский', flag: '🇷🇺', dir: 'ltr' },
    { code: 'uk', name: 'Українська', flag: '🇺🇦', dir: 'ltr' },
    { code: 'kk', name: 'Қазақша', flag: '🇰🇿', dir: 'ltr' },
    { code: 'az', name: 'Azərbaycanca', flag: '🇦🇿', dir: 'ltr' },
    { code: 'uz', name: 'O‘zbekcha', flag: '🇺🇿', dir: 'ltr' },
    { code: 'tg', name: 'Тоҷикӣ', flag: '🇹🇯', dir: 'ltr' },
    { code: 'fa', name: 'فارسی', flag: '🇮🇷', dir: 'rtl' },
    { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
    { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳', dir: 'ltr' },
    { code: 'zh', name: '中文', flag: '🇨🇳', dir: 'ltr' },
    { code: 'ja', name: '日本語', flag: '🇯🇵', dir: 'ltr' },
    { code: 'ko', name: '한국어', flag: '🇰🇷', dir: 'ltr' }
  ];

  const LOCALE_TO_INTL = {
    en: 'en-US', de: 'de-DE', es: 'es-ES', fr: 'fr-FR', it: 'it-IT', pt: 'pt-PT',
    nl: 'nl-NL', sv: 'sv-SE', no: 'nb-NO', pl: 'pl-PL', cs: 'cs-CZ', sq: 'sq-AL',
    tr: 'tr-TR', ru: 'ru-RU', uk: 'uk-UA', kk: 'kk-KZ', az: 'az-AZ', uz: 'uz-UZ',
    tg: 'tg-TJ', fa: 'fa-IR', ar: 'ar-SA', vi: 'vi-VN', zh: 'zh-CN', ja: 'ja-JP', ko: 'ko-KR'
  };

  const L = {
    en: { home:'Home',media:'Media',live:'Live',courses:'Courses',events:'Events',messages:'Messages',practice:'Practice',schedule:'Schedule',rankings:'Rankings',profile:'Profile',dashboard:'Dashboard',management:'Management',liveStudio:'Live Studio',notes:'Notes',all:'All',languages:'Languages',arts:'Arts',school:'School',search:'Search',notifications:'Notifications',upload:'Upload',publish:'Publish',title:'Title',language:'Language',level:'Level',email:'Email',role:'Role',fullName:'Full name',city:'City',country:'Country',nativeLanguage:'Native language',bio:'Bio',website:'Website',saveChanges:'Save changes',saved:'Saved ✓',signOut:'Sign out',open:'Open',close:'Close',add:'Add',send:'Send',free:'Free',teacher:'Teacher',learner:'Learner',organizer:'Organizer',organization:'Organization',admin:'Administrator',participants:'Participants',chat:'Chat',materials:'Materials',microphone:'Microphone',camera:'Camera',cameras:'Cameras',screen:'Screen',reactions:'Reactions',leave:'Leave',raiseHand:'Raise hand',lowerHand:'Lower hand',classroom:'Duvela Classroom',groupLesson:'Group lesson',lesson:'Lesson',enterLesson:'Enter lesson',cameraOff:'Camera is off',browser:'Browser',internet:'Internet',speaker:'Speaker',waitingEntry:'Waiting to enter',muteAll:'Mute all',stopCameras:'Stop cameras',lowerAllHands:'Lower all hands',writeMessage:'Write a message...',lessonMaterials:'Lesson materials',material:'Material',fullScreen:'Full screen',stop:'Stop',backToScreen:'Back to screen',copyLink:'Copy link' },
    de: { home:'Start',media:'Medien',live:'Live',courses:'Kurse',events:'Events',messages:'Nachrichten',practice:'Üben',schedule:'Zeitplan',rankings:'Ranglisten',profile:'Profil',dashboard:'Dashboard',management:'Verwaltung',liveStudio:'Live-Studio',notes:'Notizen',all:'Alle',languages:'Sprachen',arts:'Kunst',school:'Schule',search:'Suche',notifications:'Benachrichtigungen',upload:'Hochladen',publish:'Veröffentlichen',title:'Titel',language:'Sprache',level:'Niveau',email:'E-Mail',role:'Rolle',fullName:'Vollständiger Name',city:'Stadt',country:'Land',nativeLanguage:'Muttersprache',bio:'Bio',website:'Website',saveChanges:'Speichern',saved:'Gespeichert ✓',signOut:'Abmelden',open:'Öffnen',close:'Schließen',add:'Hinzufügen',send:'Senden',free:'Kostenlos',teacher:'Lehrer',learner:'Lernender',organizer:'Organisator',organization:'Organisation',admin:'Administrator',participants:'Teilnehmer',chat:'Chat',materials:'Materialien',microphone:'Mikrofon',camera:'Kamera',cameras:'Kameras',screen:'Bildschirm',reactions:'Reaktionen',leave:'Verlassen',raiseHand:'Hand heben',lowerHand:'Hand senken',classroom:'Duvela Klassenzimmer',groupLesson:'Gruppenunterricht',lesson:'Unterricht',enterLesson:'Unterricht betreten',cameraOff:'Kamera ist aus',browser:'Browser',internet:'Internet',speaker:'Lautsprecher',waitingEntry:'Warten auf Eintritt',muteAll:'Alle stummschalten',stopCameras:'Kameras stoppen',lowerAllHands:'Alle Hände senken',writeMessage:'Nachricht schreiben...',lessonMaterials:'Unterrichtsmaterialien',material:'Material',fullScreen:'Vollbild',stop:'Stoppen',backToScreen:'Zurück zum Bildschirm',copyLink:'Link kopieren' },
    es: { home:'Inicio',media:'Medios',live:'En vivo',courses:'Cursos',events:'Eventos',messages:'Mensajes',practice:'Práctica',schedule:'Horario',rankings:'Clasificación',profile:'Perfil',dashboard:'Panel',management:'Gestión',liveStudio:'Estudio en vivo',notes:'Notas',all:'Todo',languages:'Idiomas',arts:'Arte',school:'Escuela',search:'Buscar',notifications:'Notificaciones',upload:'Subir',publish:'Publicar',title:'Título',language:'Idioma',level:'Nivel',email:'Email',role:'Rol',fullName:'Nombre completo',city:'Ciudad',country:'País',nativeLanguage:'Idioma nativo',bio:'Bio',website:'Sitio web',saveChanges:'Guardar',saved:'Guardado ✓',signOut:'Salir',open:'Abrir',close:'Cerrar',add:'Añadir',send:'Enviar',free:'Gratis',teacher:'Profesor',learner:'Alumno',organizer:'Organizador',organization:'Organización',admin:'Administrador',participants:'Participantes',chat:'Chat',materials:'Materiales',microphone:'Micrófono',camera:'Cámara',cameras:'Cámaras',screen:'Pantalla',reactions:'Reacciones',leave:'Salir',raiseHand:'Levantar mano',lowerHand:'Bajar mano',classroom:'Aula Duvela',groupLesson:'Clase grupal',lesson:'Clase',enterLesson:'Entrar a clase',cameraOff:'Cámara apagada',browser:'Navegador',internet:'Internet',speaker:'Altavoz',waitingEntry:'Esperando entrada',muteAll:'Silenciar todos',stopCameras:'Apagar cámaras',lowerAllHands:'Bajar todas las manos',writeMessage:'Escribe un mensaje...',lessonMaterials:'Materiales de clase',material:'Material',fullScreen:'Pantalla completa',stop:'Detener',backToScreen:'Volver a pantalla',copyLink:'Copiar enlace' },
    fr: { home:'Accueil',media:'Média',live:'Direct',courses:'Cours',events:'Événements',messages:'Messages',practice:'Pratique',schedule:'Planning',rankings:'Classements',profile:'Profil',dashboard:'Tableau de bord',management:'Gestion',liveStudio:'Studio live',notes:'Notes',all:'Tout',languages:'Langues',arts:'Arts',school:'École',search:'Recherche',notifications:'Notifications',upload:'Importer',publish:'Publier',title:'Titre',language:'Langue',level:'Niveau',email:'Email',role:'Rôle',fullName:'Nom complet',city:'Ville',country:'Pays',nativeLanguage:'Langue maternelle',bio:'Bio',website:'Site web',saveChanges:'Enregistrer',saved:'Enregistré ✓',signOut:'Déconnexion',open:'Ouvrir',close:'Fermer',add:'Ajouter',send:'Envoyer',free:'Gratuit',teacher:'Enseignant',learner:'Apprenant',organizer:'Organisateur',organization:'Organisation',admin:'Administrateur',participants:'Participants',chat:'Chat',materials:'Supports',microphone:'Microphone',camera:'Caméra',cameras:'Caméras',screen:'Écran',reactions:'Réactions',leave:'Quitter',raiseHand:'Lever la main',lowerHand:'Baisser la main',classroom:'Classe Duvela',groupLesson:'Cours de groupe',lesson:'Cours',enterLesson:'Entrer dans le cours',cameraOff:'Caméra désactivée',browser:'Navigateur',internet:'Internet',speaker:'Haut-parleur',waitingEntry:'En attente d’entrée',muteAll:'Couper tous',stopCameras:'Arrêter les caméras',lowerAllHands:'Baisser toutes les mains',writeMessage:'Écrire un message...',lessonMaterials:'Supports de cours',material:'Support',fullScreen:'Plein écran',stop:'Arrêter',backToScreen:'Retour à l’écran',copyLink:'Copier le lien' },
    it: { home:'Home',media:'Media',live:'Live',courses:'Corsi',events:'Eventi',messages:'Messaggi',practice:'Pratica',schedule:'Calendario',rankings:'Classifiche',profile:'Profilo',dashboard:'Dashboard',management:'Gestione',liveStudio:'Studio live',notes:'Note',all:'Tutti',languages:'Lingue',arts:'Arte',school:'Scuola',search:'Cerca',notifications:'Notifiche',upload:'Carica',publish:'Pubblica',title:'Titolo',language:'Lingua',level:'Livello',email:'Email',role:'Ruolo',fullName:'Nome completo',city:'Città',country:'Paese',nativeLanguage:'Lingua madre',bio:'Bio',website:'Sito web',saveChanges:'Salva',saved:'Salvato ✓',signOut:'Esci',open:'Apri',close:'Chiudi',add:'Aggiungi',send:'Invia',free:'Gratis',teacher:'Insegnante',learner:'Studente',organizer:'Organizzatore',organization:'Organizzazione',admin:'Amministratore',participants:'Partecipanti',chat:'Chat',materials:'Materiali',microphone:'Microfono',camera:'Fotocamera',cameras:'Fotocamere',screen:'Schermo',reactions:'Reazioni',leave:'Esci',raiseHand:'Alza la mano',lowerHand:'Abbassa la mano',classroom:'Aula Duvela',groupLesson:'Lezione di gruppo',lesson:'Lezione',enterLesson:'Entra nella lezione',cameraOff:'Fotocamera spenta',browser:'Browser',internet:'Internet',speaker:'Altoparlante',waitingEntry:'In attesa di ingresso',muteAll:'Silenzia tutti',stopCameras:'Spegni fotocamere',lowerAllHands:'Abbassa tutte le mani',writeMessage:'Scrivi un messaggio...',lessonMaterials:'Materiali della lezione',material:'Materiale',fullScreen:'Schermo intero',stop:'Stop',backToScreen:'Torna allo schermo',copyLink:'Copia link' },
    pt: { home:'Início',media:'Mídia',live:'Ao vivo',courses:'Cursos',events:'Eventos',messages:'Mensagens',practice:'Prática',schedule:'Agenda',rankings:'Rankings',profile:'Perfil',dashboard:'Painel',management:'Gestão',liveStudio:'Estúdio ao vivo',notes:'Notas',all:'Todos',languages:'Idiomas',arts:'Artes',school:'Escola',search:'Buscar',notifications:'Notificações',upload:'Enviar',publish:'Publicar',title:'Título',language:'Idioma',level:'Nível',email:'Email',role:'Função',fullName:'Nome completo',city:'Cidade',country:'País',nativeLanguage:'Idioma nativo',bio:'Bio',website:'Site',saveChanges:'Salvar',saved:'Salvo ✓',signOut:'Sair',open:'Abrir',close:'Fechar',add:'Adicionar',send:'Enviar',free:'Grátis',teacher:'Professor',learner:'Aluno',organizer:'Organizador',organization:'Organização',admin:'Administrador',participants:'Participantes',chat:'Chat',materials:'Materiais',microphone:'Microfone',camera:'Câmera',cameras:'Câmeras',screen:'Tela',reactions:'Reações',leave:'Sair',raiseHand:'Levantar a mão',lowerHand:'Baixar a mão',classroom:'Sala Duvela',groupLesson:'Aula em grupo',lesson:'Aula',enterLesson:'Entrar na aula',cameraOff:'Câmera desligada',browser:'Navegador',internet:'Internet',speaker:'Alto-falante',waitingEntry:'Aguardando entrada',muteAll:'Silenciar todos',stopCameras:'Parar câmeras',lowerAllHands:'Baixar todas as mãos',writeMessage:'Escreva uma mensagem...',lessonMaterials:'Materiais da aula',material:'Material',fullScreen:'Tela cheia',stop:'Parar',backToScreen:'Voltar à tela',copyLink:'Copiar link' },
    nl: { home:'Home',media:'Media',live:'Live',courses:'Cursussen',events:'Evenementen',messages:'Berichten',practice:'Oefenen',schedule:'Planning',rankings:'Ranglijsten',profile:'Profiel',dashboard:'Dashboard',management:'Beheer',liveStudio:'Live studio',notes:'Notities',all:'Alles',languages:'Talen',arts:'Kunst',school:'School',search:'Zoeken',notifications:'Meldingen',upload:'Uploaden',publish:'Publiceren',title:'Titel',language:'Taal',level:'Niveau',email:'E-mail',role:'Rol',fullName:'Volledige naam',city:'Stad',country:'Land',nativeLanguage:'Moedertaal',bio:'Bio',website:'Website',saveChanges:'Opslaan',saved:'Opgeslagen ✓',signOut:'Uitloggen',open:'Openen',close:'Sluiten',add:'Toevoegen',send:'Verzenden',free:'Gratis',teacher:'Docent',learner:'Leerling',organizer:'Organisator',organization:'Organisatie',admin:'Beheerder',participants:'Deelnemers',chat:'Chat',materials:'Materialen',microphone:'Microfoon',camera:'Camera',cameras:'Camera’s',screen:'Scherm',reactions:'Reacties',leave:'Verlaten',raiseHand:'Hand opsteken',lowerHand:'Hand omlaag',classroom:'Duvela klaslokaal',groupLesson:'Groepsles',lesson:'Les',enterLesson:'Les binnengaan',cameraOff:'Camera uit',browser:'Browser',internet:'Internet',speaker:'Luidspreker',waitingEntry:'Wacht op toegang',muteAll:'Alles dempen',stopCameras:'Camera’s stoppen',lowerAllHands:'Alle handen omlaag',writeMessage:'Schrijf een bericht...',lessonMaterials:'Lesmateriaal',material:'Materiaal',fullScreen:'Volledig scherm',stop:'Stoppen',backToScreen:'Terug naar scherm',copyLink:'Link kopiëren' },
    sv: { home:'Hem',media:'Media',live:'Live',courses:'Kurser',events:'Evenemang',messages:'Meddelanden',practice:'Öva',schedule:'Schema',rankings:'Rankningar',profile:'Profil',dashboard:'Panel',management:'Hantering',liveStudio:'Live-studio',notes:'Anteckningar',all:'Alla',languages:'Språk',arts:'Konst',school:'Skola',search:'Sök',notifications:'Aviseringar',upload:'Ladda upp',publish:'Publicera',title:'Titel',language:'Språk',level:'Nivå',email:'E-post',role:'Roll',fullName:'Fullständigt namn',city:'Stad',country:'Land',nativeLanguage:'Modersmål',bio:'Bio',website:'Webbplats',saveChanges:'Spara',saved:'Sparat ✓',signOut:'Logga ut',open:'Öppna',close:'Stäng',add:'Lägg till',send:'Skicka',free:'Gratis',teacher:'Lärare',learner:'Elev',organizer:'Arrangör',organization:'Organisation',admin:'Administratör',participants:'Deltagare',chat:'Chatt',materials:'Material',microphone:'Mikrofon',camera:'Kamera',cameras:'Kameror',screen:'Skärm',reactions:'Reaktioner',leave:'Lämna',raiseHand:'Räck upp handen',lowerHand:'Sänk handen',classroom:'Duvela klassrum',groupLesson:'Grupplektion',lesson:'Lektion',enterLesson:'Gå in i lektionen',cameraOff:'Kameran är av',browser:'Webbläsare',internet:'Internet',speaker:'Högtalare',waitingEntry:'Väntar på inträde',muteAll:'Stäng av alla',stopCameras:'Stäng kameror',lowerAllHands:'Sänk alla händer',writeMessage:'Skriv ett meddelande...',lessonMaterials:'Lektionsmaterial',material:'Material',fullScreen:'Helskärm',stop:'Stoppa',backToScreen:'Tillbaka till skärm',copyLink:'Kopiera länk' },
    no: { home:'Hjem',media:'Media',live:'Live',courses:'Kurs',events:'Arrangementer',messages:'Meldinger',practice:'Øving',schedule:'Timeplan',rankings:'Rangeringer',profile:'Profil',dashboard:'Panel',management:'Administrasjon',liveStudio:'Live-studio',notes:'Notater',all:'Alle',languages:'Språk',arts:'Kunst',school:'Skole',search:'Søk',notifications:'Varsler',upload:'Last opp',publish:'Publiser',title:'Tittel',language:'Språk',level:'Nivå',email:'E-post',role:'Rolle',fullName:'Fullt navn',city:'By',country:'Land',nativeLanguage:'Morsmål',bio:'Bio',website:'Nettsted',saveChanges:'Lagre',saved:'Lagret ✓',signOut:'Logg ut',open:'Åpne',close:'Lukk',add:'Legg til',send:'Send',free:'Gratis',teacher:'Lærer',learner:'Elev',organizer:'Arrangør',organization:'Organisasjon',admin:'Administrator',participants:'Deltakere',chat:'Chat',materials:'Materiell',microphone:'Mikrofon',camera:'Kamera',cameras:'Kameraer',screen:'Skjerm',reactions:'Reaksjoner',leave:'Forlat',raiseHand:'Rekk opp hånden',lowerHand:'Senk hånden',classroom:'Duvela klasserom',groupLesson:'Gruppetime',lesson:'Time',enterLesson:'Gå inn i timen',cameraOff:'Kamera er av',browser:'Nettleser',internet:'Internett',speaker:'Høyttaler',waitingEntry:'Venter på tilgang',muteAll:'Demp alle',stopCameras:'Stopp kameraer',lowerAllHands:'Senk alle hender',writeMessage:'Skriv en melding...',lessonMaterials:'Timemateriell',material:'Materiell',fullScreen:'Fullskjerm',stop:'Stopp',backToScreen:'Tilbake til skjerm',copyLink:'Kopier lenke' },
    ru: { home:'Главная',media:'Медиа',live:'Эфиры',courses:'Курсы',events:'События',messages:'Сообщения',practice:'Практика',schedule:'Расписание',rankings:'Рейтинги',profile:'Профиль',dashboard:'Панель',management:'Управление',liveStudio:'LIVE-студия',notes:'Заметки',all:'Все',languages:'Языки',arts:'Искусство',school:'Школа',search:'Поиск',notifications:'Уведомления',upload:'Загрузить',publish:'Опубликовать',title:'Название',language:'Язык',level:'Уровень',email:'Email',role:'Роль',fullName:'Имя',city:'Город',country:'Страна',nativeLanguage:'Родной язык',bio:'О себе',website:'Сайт',saveChanges:'Сохранить',saved:'Сохранено ✓',signOut:'Выйти',open:'Открыть',close:'Закрыть',add:'Добавить',send:'Отправить',free:'Бесплатно',teacher:'Учитель',learner:'Ученик',organizer:'Организатор',organization:'Организация',admin:'Администратор',participants:'Участники',chat:'Чат',materials:'Материалы',microphone:'Микрофон',camera:'Камера',cameras:'Камеры',screen:'Экран',reactions:'Реакции',leave:'Выйти',raiseHand:'Поднять руку',lowerHand:'Опустить руку',classroom:'Duvela Classroom',groupLesson:'Групповой урок',lesson:'Урок',enterLesson:'Войти в урок',cameraOff:'Камера выключена',browser:'Браузер',internet:'Интернет',speaker:'Динамик',waitingEntry:'Ожидают входа',muteAll:'Всех',stopCameras:'Камеры',lowerAllHands:'Сбросить',writeMessage:'Напишите сообщение...',lessonMaterials:'Материалы урока',material:'Материал',fullScreen:'Во весь экран',stop:'Остановить',backToScreen:'Вернуться к экрану',copyLink:'Скопировать ссылку' }
  };

  ['uk','kk','az','uz','tg','fa','ar','vi','zh','ja','ko','pl','cs','sq','tr'].forEach((code) => {
    if (!L[code]) L[code] = Object.assign({}, L.en);
  });
  Object.assign(L.en, { prejoinCheck:'Check your camera and microphone before joining.', screenShare:'Screen sharing', waitingOthers:'Waiting for other participants...', chatAnswer:'Answer in chat', readiness:'Readiness', checkingDevice:'Checking device...', readyToJoin:'Ready to join.', joinWithWarnings:'You can join, but check highlighted items.', checkPermissions:'Check device permissions before joining.', micOff:'Mic off', copied:'Copied' });
  Object.assign(L.de, { prejoinCheck:'Prüfen Sie Kamera und Mikrofon vor dem Beitritt.', screenShare:'Bildschirmfreigabe', waitingOthers:'Warten auf weitere Teilnehmer...', chatAnswer:'Antwort im Chat' });
  Object.assign(L.es, { prejoinCheck:'Comprueba la cámara y el micrófono antes de entrar.', screenShare:'Compartir pantalla', waitingOthers:'Esperando a otros participantes...', chatAnswer:'Responder en chat' });
  Object.assign(L.fr, { prejoinCheck:'Vérifiez la caméra et le microphone avant d’entrer.', screenShare:'Partage d’écran', waitingOthers:'En attente des autres participants...', chatAnswer:'Réponse dans le chat' });
  Object.assign(L.ru, { prejoinCheck:'Проверьте камеру и микрофон перед входом.', screenShare:'Демонстрация экрана', waitingOthers:'Ожидаем других участников…', chatAnswer:'Ответ в чат', readiness:'Готовность', checkingDevice:'Проверяем устройство…', readyToJoin:'Можно входить.', joinWithWarnings:'Можно войти, но проверьте отмеченные пункты.', checkPermissions:'Проверьте разрешения устройств перед входом.', micOff:'Микрофон выкл.', copied:'Скопировано' });
  Object.assign(L.uk, { home:'Головна',media:'Медіа',live:'Ефіри',courses:'Курси',events:'Події',messages:'Повідомлення',practice:'Практика',schedule:'Розклад',rankings:'Рейтинги',profile:'Профіль',dashboard:'Панель',management:'Керування',liveStudio:'LIVE-студія',notes:'Нотатки',all:'Усі',languages:'Мови',arts:'Мистецтво',school:'Школа',search:'Пошук',notifications:'Сповіщення',upload:'Завантажити',publish:'Опублікувати',title:'Назва',language:'Мова',level:'Рівень',role:'Роль',fullName:'Повне ім’я',city:'Місто',country:'Країна',nativeLanguage:'Рідна мова',saveChanges:'Зберегти',saved:'Збережено ✓',signOut:'Вийти',open:'Відкрити',close:'Закрити',add:'Додати',send:'Надіслати',free:'Безкоштовно',teacher:'Вчитель',learner:'Учень',organizer:'Організатор',organization:'Організація',admin:'Адміністратор',participants:'Учасники',chat:'Чат',materials:'Матеріали',microphone:'Мікрофон',camera:'Камера',cameras:'Камери',screen:'Екран',reactions:'Реакції',leave:'Вийти',raiseHand:'Підняти руку',lowerHand:'Опустити руку',classroom:'Duvela Classroom',groupLesson:'Груповий урок',lesson:'Урок',enterLesson:'Увійти в урок',cameraOff:'Камера вимкнена',browser:'Браузер',internet:'Інтернет',speaker:'Динамік',waitingEntry:'Очікують входу',muteAll:'Вимкнути всіх',stopCameras:'Вимкнути камери',lowerAllHands:'Опустити всі руки',writeMessage:'Напишіть повідомлення...',lessonMaterials:'Матеріали уроку',material:'Матеріал',fullScreen:'На весь екран',stop:'Зупинити',backToScreen:'Повернутися до екрана',copyLink:'Скопіювати посилання' });
  Object.assign(L.kk, { home:'Басты бет',media:'Медиа',live:'Тікелей эфир',courses:'Курстар',events:'Оқиғалар',messages:'Хабарламалар',practice:'Тәжірибе',schedule:'Кесте',rankings:'Рейтингтер',profile:'Профиль',dashboard:'Панель',management:'Басқару',liveStudio:'LIVE студия',notes:'Жазбалар',all:'Барлығы',languages:'Тілдер',arts:'Өнер',school:'Мектеп',search:'Іздеу',notifications:'Хабарландырулар',upload:'Жүктеу',publish:'Жариялау',title:'Атауы',language:'Тіл',level:'Деңгей',role:'Рөл',fullName:'Толық аты',city:'Қала',country:'Ел',nativeLanguage:'Ана тілі',saveChanges:'Сақтау',saved:'Сақталды ✓',signOut:'Шығу',open:'Ашу',close:'Жабу',add:'Қосу',send:'Жіберу',free:'Тегін',teacher:'Мұғалім',learner:'Оқушы',organizer:'Ұйымдастырушы',organization:'Ұйым',admin:'Әкімші',participants:'Қатысушылар',chat:'Чат',materials:'Материалдар',microphone:'Микрофон',camera:'Камера',cameras:'Камералар',screen:'Экран',reactions:'Реакциялар',leave:'Шығу',raiseHand:'Қол көтеру',lowerHand:'Қолды түсіру',groupLesson:'Топтық сабақ',lesson:'Сабақ',enterLesson:'Сабаққа кіру',cameraOff:'Камера өшірулі',browser:'Браузер',internet:'Интернет',speaker:'Динамик',waitingEntry:'Кіруді күтуде',muteAll:'Барлығын өшіру',stopCameras:'Камераларды тоқтату',lowerAllHands:'Барлық қолды түсіру',writeMessage:'Хабарлама жазыңыз...',lessonMaterials:'Сабақ материалдары',material:'Материал',fullScreen:'Толық экран',stop:'Тоқтату',backToScreen:'Экранға қайту',copyLink:'Сілтемені көшіру' });
  Object.assign(L.az, { home:'Ana səhifə',media:'Media',live:'Canlı',courses:'Kurslar',events:'Tədbirlər',messages:'Mesajlar',practice:'Məşq',schedule:'Cədvəl',rankings:'Reytinqlər',profile:'Profil',dashboard:'Panel',management:'İdarəetmə',liveStudio:'Canlı studiya',notes:'Qeydlər',all:'Hamısı',languages:'Dillər',arts:'İncəsənət',school:'Məktəb',search:'Axtar',notifications:'Bildirişlər',upload:'Yüklə',publish:'Dərc et',title:'Başlıq',language:'Dil',level:'Səviyyə',role:'Rol',fullName:'Tam ad',city:'Şəhər',country:'Ölkə',nativeLanguage:'Ana dili',saveChanges:'Saxla',saved:'Saxlandı ✓',signOut:'Çıxış',open:'Aç',close:'Bağla',add:'Əlavə et',send:'Göndər',free:'Pulsuz',teacher:'Müəllim',learner:'Şagird',organizer:'Təşkilatçı',organization:'Təşkilat',admin:'Administrator',participants:'İştirakçılar',chat:'Çat',materials:'Materiallar',microphone:'Mikrofon',camera:'Kamera',cameras:'Kameralar',screen:'Ekran',reactions:'Reaksiyalar',leave:'Çıx',raiseHand:'Əl qaldır',lowerHand:'Əli endir',groupLesson:'Qrup dərsi',lesson:'Dərs',enterLesson:'Dərsə daxil ol',cameraOff:'Kamera söndürülüb',browser:'Brauzer',internet:'İnternet',speaker:'Dinamik',waitingEntry:'Giriş gözləyir',muteAll:'Hamını səssiz et',stopCameras:'Kameraları dayandır',lowerAllHands:'Bütün əlləri endir',writeMessage:'Mesaj yazın...',lessonMaterials:'Dərs materialları',material:'Material',fullScreen:'Tam ekran',stop:'Dayandır',backToScreen:'Ekrana qayıt',copyLink:'Linki kopyala' });
  Object.assign(L.uz, { home:'Bosh sahifa',media:'Media',live:'Jonli',courses:'Kurslar',events:'Tadbirlar',messages:'Xabarlar',practice:'Mashq',schedule:'Jadval',rankings:'Reytinglar',profile:'Profil',dashboard:'Panel',management:'Boshqaruv',liveStudio:'Jonli studiya',notes:'Eslatmalar',all:'Hammasi',languages:'Tillar',arts:'San’at',school:'Maktab',search:'Qidirish',notifications:'Bildirishnomalar',upload:'Yuklash',publish:'Nashr qilish',title:'Sarlavha',language:'Til',level:'Daraja',role:'Rol',fullName:'To‘liq ism',city:'Shahar',country:'Mamlakat',nativeLanguage:'Ona tili',saveChanges:'Saqlash',saved:'Saqlandi ✓',signOut:'Chiqish',open:'Ochish',close:'Yopish',add:'Qo‘shish',send:'Yuborish',free:'Bepul',teacher:'O‘qituvchi',learner:'O‘quvchi',organizer:'Tashkilotchi',organization:'Tashkilot',admin:'Administrator',participants:'Ishtirokchilar',chat:'Chat',materials:'Materiallar',microphone:'Mikrofon',camera:'Kamera',cameras:'Kameralar',screen:'Ekran',reactions:'Reaksiyalar',leave:'Chiqish',raiseHand:'Qo‘l ko‘tarish',lowerHand:'Qo‘lni tushirish',groupLesson:'Guruh darsi',lesson:'Dars',enterLesson:'Darsga kirish',cameraOff:'Kamera o‘chiq',browser:'Brauzer',internet:'Internet',speaker:'Karnay',waitingEntry:'Kirish kutilmoqda',muteAll:'Hammani ovozsiz qilish',stopCameras:'Kameralarni to‘xtatish',lowerAllHands:'Barcha qo‘llarni tushirish',writeMessage:'Xabar yozing...',lessonMaterials:'Dars materiallari',material:'Material',fullScreen:'To‘liq ekran',stop:'To‘xtatish',backToScreen:'Ekranga qaytish',copyLink:'Havolani nusxalash' });
  Object.assign(L.tg, { home:'Асосӣ',media:'Медиа',live:'Зинда',courses:'Курсҳо',events:'Рӯйдодҳо',messages:'Паёмҳо',practice:'Машқ',schedule:'Ҷадвал',rankings:'Рейтингҳо',profile:'Профил',dashboard:'Панел',management:'Идоракунӣ',liveStudio:'Студияи зинда',notes:'Қайдҳо',all:'Ҳама',languages:'Забонҳо',arts:'Санъат',school:'Мактаб',search:'Ҷустуҷӯ',notifications:'Огоҳиномаҳо',upload:'Боргузорӣ',publish:'Нашр',title:'Унвон',language:'Забон',level:'Сатҳ',role:'Нақш',fullName:'Номи пурра',city:'Шаҳр',country:'Кишвар',nativeLanguage:'Забони модарӣ',saveChanges:'Сабт',saved:'Сабт шуд ✓',signOut:'Баромад',open:'Кушодан',close:'Пӯшидан',add:'Илова',send:'Фиристодан',free:'Ройгон',teacher:'Омӯзгор',learner:'Донишомӯз',organizer:'Ташкилкунанда',organization:'Ташкилот',admin:'Маъмур',participants:'Иштирокчиён',chat:'Чат',materials:'Маводҳо',microphone:'Микрофон',camera:'Камера',cameras:'Камераҳо',screen:'Экран',reactions:'Вокунишҳо',leave:'Баромадан',raiseHand:'Даст бардоштан',lowerHand:'Дастро поён кардан',groupLesson:'Дарси гурӯҳӣ',lesson:'Дарс',enterLesson:'Ба дарс ворид шудан',cameraOff:'Камера хомӯш аст',browser:'Браузер',internet:'Интернет',speaker:'Баландгӯяк',waitingEntry:'Интизори воридшавӣ',muteAll:'Ҳамаро хомӯш кардан',stopCameras:'Камераҳоро қатъ кардан',lowerAllHands:'Ҳама дастҳоро поён кардан',writeMessage:'Паём нависед...',lessonMaterials:'Маводҳои дарс',material:'Мавод',fullScreen:'Экрани пурра',stop:'Қатъ',backToScreen:'Бозгашт ба экран',copyLink:'Нусхабардории пайванд' });
  Object.assign(L.sq, { home:'Kryefaqja',media:'Media',live:'Live',courses:'Kurse',events:'Ngjarje',messages:'Mesazhe',practice:'Praktikë',schedule:'Orari',rankings:'Renditje',profile:'Profili',dashboard:'Paneli',management:'Menaxhim',liveStudio:'Studio live',notes:'Shënime',all:'Të gjitha',languages:'Gjuhë',arts:'Arte',school:'Shkollë',search:'Kërko',notifications:'Njoftime',upload:'Ngarko',publish:'Publiko',title:'Titulli',language:'Gjuha',level:'Niveli',role:'Roli',fullName:'Emri i plotë',city:'Qyteti',country:'Shteti',nativeLanguage:'Gjuha amtare',saveChanges:'Ruaj',saved:'U ruajt ✓',signOut:'Dil',open:'Hap',close:'Mbyll',add:'Shto',send:'Dërgo',free:'Falas',teacher:'Mësues',learner:'Nxënës',organizer:'Organizator',organization:'Organizatë',admin:'Administrator',participants:'Pjesëmarrës',chat:'Chat',materials:'Materiale',microphone:'Mikrofon',camera:'Kamera',cameras:'Kamera',screen:'Ekran',reactions:'Reagime',leave:'Dil',raiseHand:'Ngrit dorën',lowerHand:'Ul dorën',groupLesson:'Mësim në grup',lesson:'Mësim',enterLesson:'Hyr në mësim',cameraOff:'Kamera është fikur',browser:'Shfletues',internet:'Internet',speaker:'Altoparlant',waitingEntry:'Në pritje për hyrje',muteAll:'Hesht të gjithë',stopCameras:'Ndalo kamerat',lowerAllHands:'Ul të gjitha duart',writeMessage:'Shkruaj një mesazh...',lessonMaterials:'Materialet e mësimit',material:'Material',fullScreen:'Ekran i plotë',stop:'Ndalo',backToScreen:'Kthehu te ekrani',copyLink:'Kopjo lidhjen' });
  Object.assign(L.pl, { home:'Start',media:'Media',live:'Na żywo',courses:'Kursy',events:'Wydarzenia',messages:'Wiadomości',practice:'Praktyka',schedule:'Plan',rankings:'Rankingi',profile:'Profil',dashboard:'Panel',management:'Zarządzanie',liveStudio:'Studio live',notes:'Notatki',all:'Wszystko',languages:'Języki',arts:'Sztuka',school:'Szkoła',search:'Szukaj',notifications:'Powiadomienia',upload:'Prześlij',publish:'Opublikuj',title:'Tytuł',language:'Język',level:'Poziom',role:'Rola',fullName:'Pełne imię',city:'Miasto',country:'Kraj',nativeLanguage:'Język ojczysty',saveChanges:'Zapisz',saved:'Zapisano ✓',signOut:'Wyloguj',open:'Otwórz',close:'Zamknij',add:'Dodaj',send:'Wyślij',free:'Bezpłatnie',teacher:'Nauczyciel',learner:'Uczeń',organizer:'Organizator',organization:'Organizacja',admin:'Administrator',participants:'Uczestnicy',materials:'Materiały',microphone:'Mikrofon',camera:'Kamera',cameras:'Kamery',screen:'Ekran',reactions:'Reakcje',leave:'Wyjdź',raiseHand:'Podnieś rękę',lowerHand:'Opuść rękę',classroom:'Klasa Duvela',groupLesson:'Lekcja grupowa',lesson:'Lekcja',enterLesson:'Wejdź na lekcję',cameraOff:'Kamera wyłączona',browser:'Przeglądarka',speaker:'Głośnik',waitingEntry:'Czekają na wejście',muteAll:'Wycisz wszystkich',stopCameras:'Zatrzymaj kamery',lowerAllHands:'Opuść wszystkie ręce',writeMessage:'Napisz wiadomość...',lessonMaterials:'Materiały lekcji',material:'Materiał',fullScreen:'Pełny ekran',stop:'Zatrzymaj',backToScreen:'Powrót do ekranu',copyLink:'Kopiuj link' });
  Object.assign(L.cs, { home:'Domů',media:'Média',live:'Živě',courses:'Kurzy',events:'Události',messages:'Zprávy',practice:'Praxe',schedule:'Rozvrh',rankings:'Žebříčky',profile:'Profil',dashboard:'Panel',management:'Správa',liveStudio:'Live studio',notes:'Poznámky',all:'Vše',languages:'Jazyky',arts:'Umění',school:'Škola',search:'Hledat',notifications:'Oznámení',upload:'Nahrát',publish:'Publikovat',title:'Název',language:'Jazyk',level:'Úroveň',role:'Role',fullName:'Celé jméno',city:'Město',country:'Země',nativeLanguage:'Mateřský jazyk',saveChanges:'Uložit',saved:'Uloženo ✓',signOut:'Odhlásit',open:'Otevřít',close:'Zavřít',add:'Přidat',send:'Odeslat',free:'Zdarma',teacher:'Učitel',learner:'Student',organizer:'Organizátor',organization:'Organizace',admin:'Administrátor',participants:'Účastníci',materials:'Materiály',microphone:'Mikrofon',camera:'Kamera',cameras:'Kamery',screen:'Obrazovka',reactions:'Reakce',leave:'Odejít',raiseHand:'Zvednout ruku',lowerHand:'Spustit ruku',classroom:'Učebna Duvela',groupLesson:'Skupinová lekce',lesson:'Lekce',enterLesson:'Vstoupit do lekce',cameraOff:'Kamera vypnutá',browser:'Prohlížeč',speaker:'Reproduktor',waitingEntry:'Čekají na vstup',muteAll:'Ztlumit všechny',stopCameras:'Vypnout kamery',lowerAllHands:'Spustit všechny ruce',writeMessage:'Napište zprávu...',lessonMaterials:'Materiály lekce',material:'Materiál',fullScreen:'Celá obrazovka',stop:'Zastavit',backToScreen:'Zpět na obrazovku',copyLink:'Kopírovat odkaz' });
  Object.assign(L.tr, { home:'Ana sayfa',media:'Medya',live:'Canlı',courses:'Kurslar',events:'Etkinlikler',messages:'Mesajlar',practice:'Pratik',schedule:'Takvim',rankings:'Sıralamalar',profile:'Profil',dashboard:'Panel',management:'Yönetim',liveStudio:'Canlı stüdyo',notes:'Notlar',all:'Tümü',languages:'Diller',arts:'Sanat',school:'Okul',search:'Ara',notifications:'Bildirimler',upload:'Yükle',publish:'Yayınla',title:'Başlık',language:'Dil',level:'Seviye',role:'Rol',fullName:'Tam ad',city:'Şehir',country:'Ülke',nativeLanguage:'Ana dil',saveChanges:'Kaydet',saved:'Kaydedildi ✓',signOut:'Çıkış yap',open:'Aç',close:'Kapat',add:'Ekle',send:'Gönder',free:'Ücretsiz',teacher:'Öğretmen',learner:'Öğrenci',organizer:'Organizatör',organization:'Organizasyon',admin:'Yönetici',participants:'Katılımcılar',materials:'Materyaller',microphone:'Mikrofon',camera:'Kamera',cameras:'Kameralar',screen:'Ekran',reactions:'Tepkiler',leave:'Ayrıl',raiseHand:'El kaldır',lowerHand:'Eli indir',classroom:'Duvela Sınıfı',groupLesson:'Grup dersi',lesson:'Ders',enterLesson:'Derse gir',cameraOff:'Kamera kapalı',browser:'Tarayıcı',speaker:'Hoparlör',waitingEntry:'Giriş bekleyenler',muteAll:'Herkesi sustur',stopCameras:'Kameraları kapat',lowerAllHands:'Tüm elleri indir',writeMessage:'Mesaj yaz...',lessonMaterials:'Ders materyalleri',material:'Materyal',fullScreen:'Tam ekran',stop:'Durdur',backToScreen:'Ekrana dön',copyLink:'Bağlantıyı kopyala' });
  Object.assign(L.fa, { home:'خانه',media:'رسانه',live:'زنده',courses:'دوره‌ها',events:'رویدادها',messages:'پیام‌ها',practice:'تمرین',schedule:'برنامه',rankings:'رتبه‌بندی',profile:'پروفایل',dashboard:'داشبورد',management:'مدیریت',liveStudio:'استودیوی زنده',notes:'یادداشت‌ها',all:'همه',languages:'زبان‌ها',arts:'هنرها',school:'مدرسه',search:'جستجو',notifications:'اعلان‌ها',upload:'بارگذاری',publish:'انتشار',title:'عنوان',language:'زبان',level:'سطح',role:'نقش',fullName:'نام کامل',city:'شهر',country:'کشور',nativeLanguage:'زبان مادری',saveChanges:'ذخیره',saved:'ذخیره شد ✓',signOut:'خروج',open:'باز کردن',close:'بستن',add:'افزودن',send:'ارسال',free:'رایگان',teacher:'معلم',learner:'دانش‌آموز',organizer:'برگزارکننده',organization:'سازمان',admin:'مدیر',participants:'شرکت‌کنندگان',materials:'مواد',microphone:'میکروفون',camera:'دوربین',cameras:'دوربین‌ها',screen:'صفحه',reactions:'واکنش‌ها',leave:'ترک',raiseHand:'بالا بردن دست',lowerHand:'پایین آوردن دست',classroom:'کلاس Duvela',groupLesson:'درس گروهی',lesson:'درس',enterLesson:'ورود به درس',cameraOff:'دوربین خاموش است',browser:'مرورگر',speaker:'بلندگو',waitingEntry:'در انتظار ورود',muteAll:'بی‌صدا کردن همه',stopCameras:'توقف دوربین‌ها',lowerAllHands:'پایین آوردن همه دست‌ها',writeMessage:'پیام بنویسید...',lessonMaterials:'مواد درس',material:'ماده',fullScreen:'تمام صفحه',stop:'توقف',backToScreen:'بازگشت به صفحه',copyLink:'کپی لینک' });
  Object.assign(L.ar, { home:'الرئيسية',media:'الوسائط',live:'مباشر',courses:'الدورات',events:'الفعاليات',messages:'الرسائل',practice:'تدريب',schedule:'الجدول',rankings:'الترتيب',profile:'الملف الشخصي',dashboard:'لوحة التحكم',management:'الإدارة',liveStudio:'استوديو مباشر',notes:'ملاحظات',all:'الكل',languages:'اللغات',arts:'الفنون',school:'المدرسة',search:'بحث',notifications:'الإشعارات',upload:'رفع',publish:'نشر',title:'العنوان',language:'اللغة',level:'المستوى',role:'الدور',fullName:'الاسم الكامل',city:'المدينة',country:'البلد',nativeLanguage:'اللغة الأم',saveChanges:'حفظ',saved:'تم الحفظ ✓',signOut:'تسجيل الخروج',open:'فتح',close:'إغلاق',add:'إضافة',send:'إرسال',free:'مجاني',teacher:'المعلم',learner:'الطالب',organizer:'المنظم',organization:'المنظمة',admin:'المشرف',participants:'المشاركون',materials:'المواد',microphone:'الميكروفون',camera:'الكاميرا',cameras:'الكاميرات',screen:'الشاشة',reactions:'التفاعلات',leave:'مغادرة',raiseHand:'رفع اليد',lowerHand:'خفض اليد',classroom:'فصل Duvela',groupLesson:'درس جماعي',lesson:'درس',enterLesson:'دخول الدرس',cameraOff:'الكاميرا مغلقة',browser:'المتصفح',speaker:'السماعة',waitingEntry:'بانتظار الدخول',muteAll:'كتم الجميع',stopCameras:'إيقاف الكاميرات',lowerAllHands:'خفض كل الأيدي',writeMessage:'اكتب رسالة...',lessonMaterials:'مواد الدرس',material:'مادة',fullScreen:'ملء الشاشة',stop:'إيقاف',backToScreen:'العودة إلى الشاشة',copyLink:'نسخ الرابط' });
  Object.assign(L.vi, { home:'Trang chủ',media:'Media',live:'Trực tiếp',courses:'Khóa học',events:'Sự kiện',messages:'Tin nhắn',practice:'Luyện tập',schedule:'Lịch',rankings:'Xếp hạng',profile:'Hồ sơ',dashboard:'Bảng điều khiển',management:'Quản lý',liveStudio:'Studio trực tiếp',notes:'Ghi chú',all:'Tất cả',languages:'Ngôn ngữ',arts:'Nghệ thuật',school:'Trường học',search:'Tìm kiếm',notifications:'Thông báo',upload:'Tải lên',publish:'Đăng',title:'Tiêu đề',language:'Ngôn ngữ',level:'Trình độ',role:'Vai trò',fullName:'Họ tên',city:'Thành phố',country:'Quốc gia',nativeLanguage:'Tiếng mẹ đẻ',saveChanges:'Lưu',saved:'Đã lưu ✓',signOut:'Đăng xuất',open:'Mở',close:'Đóng',add:'Thêm',send:'Gửi',free:'Miễn phí',teacher:'Giáo viên',learner:'Học viên',organizer:'Người tổ chức',organization:'Tổ chức',admin:'Quản trị viên',participants:'Người tham gia',materials:'Tài liệu',microphone:'Micrô',camera:'Camera',cameras:'Camera',screen:'Màn hình',reactions:'Cảm xúc',leave:'Rời khỏi',raiseHand:'Giơ tay',lowerHand:'Hạ tay',classroom:'Lớp học Duvela',groupLesson:'Bài học nhóm',lesson:'Bài học',enterLesson:'Vào lớp',cameraOff:'Camera đang tắt',browser:'Trình duyệt',speaker:'Loa',waitingEntry:'Đang chờ vào',muteAll:'Tắt tiếng tất cả',stopCameras:'Tắt camera',lowerAllHands:'Hạ tất cả tay',writeMessage:'Viết tin nhắn...',lessonMaterials:'Tài liệu bài học',material:'Tài liệu',fullScreen:'Toàn màn hình',stop:'Dừng',backToScreen:'Quay lại màn hình',copyLink:'Sao chép liên kết' });
  Object.assign(L.zh, { home:'首页',media:'媒体',live:'直播',courses:'课程',events:'活动',messages:'消息',practice:'练习',schedule:'日程',rankings:'排名',profile:'个人资料',dashboard:'仪表盘',management:'管理',liveStudio:'直播工作室',notes:'笔记',all:'全部',languages:'语言',arts:'艺术',school:'学校',search:'搜索',notifications:'通知',upload:'上传',publish:'发布',title:'标题',language:'语言',level:'级别',role:'角色',fullName:'全名',city:'城市',country:'国家',nativeLanguage:'母语',saveChanges:'保存',saved:'已保存 ✓',signOut:'退出',open:'打开',close:'关闭',add:'添加',send:'发送',free:'免费',teacher:'教师',learner:'学生',organizer:'组织者',organization:'组织',admin:'管理员',participants:'参与者',materials:'材料',microphone:'麦克风',camera:'摄像头',cameras:'摄像头',screen:'屏幕',reactions:'反应',leave:'离开',raiseHand:'举手',lowerHand:'放下手',classroom:'Duvela 课堂',groupLesson:'小组课',lesson:'课程',enterLesson:'进入课程',cameraOff:'摄像头已关闭',browser:'浏览器',speaker:'扬声器',waitingEntry:'等待进入',muteAll:'全部静音',stopCameras:'关闭摄像头',lowerAllHands:'放下所有手',writeMessage:'输入消息...',lessonMaterials:'课程材料',material:'材料',fullScreen:'全屏',stop:'停止',backToScreen:'返回屏幕',copyLink:'复制链接' });
  Object.assign(L.ja, { home:'ホーム',media:'メディア',live:'ライブ',courses:'コース',events:'イベント',messages:'メッセージ',practice:'練習',schedule:'スケジュール',rankings:'ランキング',profile:'プロフィール',dashboard:'ダッシュボード',management:'管理',liveStudio:'ライブスタジオ',notes:'ノート',all:'すべて',languages:'言語',arts:'アート',school:'学校',search:'検索',notifications:'通知',upload:'アップロード',publish:'公開',title:'タイトル',language:'言語',level:'レベル',role:'役割',fullName:'氏名',city:'都市',country:'国',nativeLanguage:'母語',saveChanges:'保存',saved:'保存済み ✓',signOut:'サインアウト',open:'開く',close:'閉じる',add:'追加',send:'送信',free:'無料',teacher:'教師',learner:'学習者',organizer:'主催者',organization:'組織',admin:'管理者',participants:'参加者',materials:'教材',microphone:'マイク',camera:'カメラ',cameras:'カメラ',screen:'画面',reactions:'リアクション',leave:'退出',raiseHand:'手を挙げる',lowerHand:'手を下げる',classroom:'Duvela Classroom',groupLesson:'グループレッスン',lesson:'レッスン',enterLesson:'レッスンに入る',cameraOff:'カメラはオフです',browser:'ブラウザ',speaker:'スピーカー',waitingEntry:'入室待ち',muteAll:'全員ミュート',stopCameras:'カメラ停止',lowerAllHands:'全員の手を下げる',writeMessage:'メッセージを書く...',lessonMaterials:'レッスン教材',material:'教材',fullScreen:'全画面',stop:'停止',backToScreen:'画面に戻る',copyLink:'リンクをコピー' });
  Object.assign(L.ko, { home:'홈',media:'미디어',live:'라이브',courses:'강좌',events:'이벤트',messages:'메시지',practice:'연습',schedule:'일정',rankings:'순위',profile:'프로필',dashboard:'대시보드',management:'관리',liveStudio:'라이브 스튜디오',notes:'노트',all:'전체',languages:'언어',arts:'예술',school:'학교',search:'검색',notifications:'알림',upload:'업로드',publish:'게시',title:'제목',language:'언어',level:'레벨',role:'역할',fullName:'전체 이름',city:'도시',country:'국가',nativeLanguage:'모국어',saveChanges:'저장',saved:'저장됨 ✓',signOut:'로그아웃',open:'열기',close:'닫기',add:'추가',send:'보내기',free:'무료',teacher:'교사',learner:'학습자',organizer:'주최자',organization:'조직',admin:'관리자',participants:'참가자',materials:'자료',microphone:'마이크',camera:'카메라',cameras:'카메라',screen:'화면',reactions:'반응',leave:'나가기',raiseHand:'손 들기',lowerHand:'손 내리기',classroom:'Duvela 교실',groupLesson:'그룹 수업',lesson:'수업',enterLesson:'수업 입장',cameraOff:'카메라 꺼짐',browser:'브라우저',speaker:'스피커',waitingEntry:'입장 대기',muteAll:'모두 음소거',stopCameras:'카메라 중지',lowerAllHands:'모든 손 내리기',writeMessage:'메시지 작성...',lessonMaterials:'수업 자료',material:'자료',fullScreen:'전체 화면',stop:'중지',backToScreen:'화면으로 돌아가기',copyLink:'링크 복사' });

  const CLASSROOM_EXTRA = {
    en: { online:'online', weakConnection:'weak connection', connectionStable:'Connection looks stable', watch:'Watch', showEveryone:'Show everyone', viewOnly:'View only', materialsUnavailable:'Materials are not available yet.', noMaterials:'No materials for this lesson yet.', pdfOpensOutside:'PDF opens outside the classroom', pdfPreviewBlocked:'Browsers block this PDF preview, so use a new tab for reliable viewing.', openMaterialNewTab:'Open this material in a new tab', fileCannotPreview:'This file type cannot be previewed inside the classroom.', openPdf:'Open PDF' },
    de: { online:'online', weakConnection:'schwache Verbindung', connectionStable:'Verbindung wirkt stabil', watch:'Ansehen', showEveryone:'Allen zeigen', viewOnly:'Nur ansehen', materialsUnavailable:'Materialien sind noch nicht verfügbar.', noMaterials:'Noch keine Materialien für diese Lektion.', pdfOpensOutside:'PDF öffnet außerhalb des Klassenzimmers', pdfPreviewBlocked:'Browser blockieren diese PDF-Vorschau. Öffnen Sie sie zuverlässig in einem neuen Tab.', openMaterialNewTab:'Dieses Material in einem neuen Tab öffnen', fileCannotPreview:'Dieser Dateityp kann im Klassenzimmer nicht angezeigt werden.', openPdf:'PDF öffnen' },
    es: { online:'en línea', weakConnection:'conexión débil', connectionStable:'La conexión parece estable', watch:'Ver', showEveryone:'Mostrar a todos', viewOnly:'Solo ver', materialsUnavailable:'Los materiales aún no están disponibles.', noMaterials:'Aún no hay materiales para esta clase.', pdfOpensOutside:'El PDF se abre fuera del aula', pdfPreviewBlocked:'El navegador bloquea esta vista previa de PDF. Ábrelo en una nueva pestaña.', openMaterialNewTab:'Abrir este material en una pestaña nueva', fileCannotPreview:'Este tipo de archivo no se puede previsualizar dentro del aula.', openPdf:'Abrir PDF' },
    fr: { online:'en ligne', weakConnection:'connexion faible', connectionStable:'La connexion semble stable', watch:'Voir', showEveryone:'Montrer à tous', viewOnly:'Lecture seule', materialsUnavailable:'Les supports ne sont pas encore disponibles.', noMaterials:'Aucun support pour ce cours pour le moment.', pdfOpensOutside:'Le PDF s’ouvre hors de la classe', pdfPreviewBlocked:'Le navigateur bloque cet aperçu PDF. Ouvrez-le dans un nouvel onglet.', openMaterialNewTab:'Ouvrir ce support dans un nouvel onglet', fileCannotPreview:'Ce type de fichier ne peut pas être prévisualisé dans la classe.', openPdf:'Ouvrir le PDF' },
    it: { online:'online', weakConnection:'connessione debole', connectionStable:'La connessione sembra stabile', watch:'Guarda', showEveryone:'Mostra a tutti', viewOnly:'Solo visualizzazione', materialsUnavailable:'I materiali non sono ancora disponibili.', noMaterials:'Nessun materiale per questa lezione.', pdfOpensOutside:'Il PDF si apre fuori dall’aula', pdfPreviewBlocked:'Il browser blocca questa anteprima PDF. Aprilo in una nuova scheda.', openMaterialNewTab:'Apri questo materiale in una nuova scheda', fileCannotPreview:'Questo tipo di file non può essere visualizzato nell’aula.', openPdf:'Apri PDF' },
    pt: { online:'online', weakConnection:'conexão fraca', connectionStable:'A conexão parece estável', watch:'Ver', showEveryone:'Mostrar a todos', viewOnly:'Somente visualização', materialsUnavailable:'Os materiais ainda não estão disponíveis.', noMaterials:'Ainda não há materiais para esta aula.', pdfOpensOutside:'O PDF abre fora da sala', pdfPreviewBlocked:'O navegador bloqueia esta prévia de PDF. Abra em uma nova aba.', openMaterialNewTab:'Abrir este material em uma nova aba', fileCannotPreview:'Este tipo de arquivo não pode ser pré-visualizado na sala.', openPdf:'Abrir PDF' },
    nl: { online:'online', weakConnection:'zwakke verbinding', connectionStable:'Verbinding lijkt stabiel', watch:'Bekijken', showEveryone:'Aan iedereen tonen', viewOnly:'Alleen bekijken', materialsUnavailable:'Materialen zijn nog niet beschikbaar.', noMaterials:'Nog geen materiaal voor deze les.', pdfOpensOutside:'PDF opent buiten het klaslokaal', pdfPreviewBlocked:'De browser blokkeert deze PDF-preview. Open hem in een nieuw tabblad.', openMaterialNewTab:'Dit materiaal in een nieuw tabblad openen', fileCannotPreview:'Dit bestandstype kan niet in het klaslokaal worden bekeken.', openPdf:'PDF openen' },
    sv: { online:'online', weakConnection:'svag anslutning', connectionStable:'Anslutningen verkar stabil', watch:'Visa', showEveryone:'Visa för alla', viewOnly:'Endast visning', materialsUnavailable:'Materialen är inte tillgängliga ännu.', noMaterials:'Inga material för denna lektion ännu.', pdfOpensOutside:'PDF öppnas utanför klassrummet', pdfPreviewBlocked:'Webbläsaren blockerar PDF-förhandsvisningen. Öppna i en ny flik.', openMaterialNewTab:'Öppna materialet i en ny flik', fileCannotPreview:'Den här filtypen kan inte förhandsvisas i klassrummet.', openPdf:'Öppna PDF' },
    no: { online:'på nett', weakConnection:'svak tilkobling', connectionStable:'Tilkoblingen virker stabil', watch:'Se', showEveryone:'Vis til alle', viewOnly:'Kun visning', materialsUnavailable:'Materialer er ikke tilgjengelige ennå.', noMaterials:'Ingen materialer for denne timen ennå.', pdfOpensOutside:'PDF åpnes utenfor klasserommet', pdfPreviewBlocked:'Nettleseren blokkerer denne PDF-forhåndsvisningen. Åpne i en ny fane.', openMaterialNewTab:'Åpne dette materialet i en ny fane', fileCannotPreview:'Denne filtypen kan ikke forhåndsvises i klasserommet.', openPdf:'Åpne PDF' },
    pl: { online:'online', weakConnection:'słabe połączenie', connectionStable:'Połączenie wygląda stabilnie', watch:'Zobacz', showEveryone:'Pokaż wszystkim', viewOnly:'Tylko podgląd', materialsUnavailable:'Materiały nie są jeszcze dostępne.', noMaterials:'Brak materiałów dla tej lekcji.', pdfOpensOutside:'PDF otwiera się poza klasą', pdfPreviewBlocked:'Przeglądarka blokuje podgląd PDF. Otwórz go w nowej karcie.', openMaterialNewTab:'Otwórz materiał w nowej karcie', fileCannotPreview:'Tego typu pliku nie można podejrzeć w klasie.', openPdf:'Otwórz PDF' },
    cs: { online:'online', weakConnection:'slabé připojení', connectionStable:'Připojení vypadá stabilně', watch:'Zobrazit', showEveryone:'Ukázat všem', viewOnly:'Pouze náhled', materialsUnavailable:'Materiály zatím nejsou dostupné.', noMaterials:'Zatím žádné materiály pro tuto lekci.', pdfOpensOutside:'PDF se otevře mimo učebnu', pdfPreviewBlocked:'Prohlížeč blokuje náhled PDF. Otevřete ho v nové kartě.', openMaterialNewTab:'Otevřít materiál v nové kartě', fileCannotPreview:'Tento typ souboru nelze v učebně zobrazit.', openPdf:'Otevřít PDF' },
    sq: { online:'online', weakConnection:'lidhje e dobët', connectionStable:'Lidhja duket stabile', watch:'Shiko', showEveryone:'Shfaqe për të gjithë', viewOnly:'Vetëm shikim', materialsUnavailable:'Materialet nuk janë ende të disponueshme.', noMaterials:'Ende nuk ka materiale për këtë mësim.', pdfOpensOutside:'PDF hapet jashtë klasës', pdfPreviewBlocked:'Shfletuesi bllokon pamjen PDF. Hape në një skedë të re.', openMaterialNewTab:'Hape këtë material në një skedë të re', fileCannotPreview:'Ky lloj skedari nuk mund të shfaqet brenda klasës.', openPdf:'Hap PDF' },
    tr: { online:'çevrimiçi', weakConnection:'zayıf bağlantı', connectionStable:'Bağlantı stabil görünüyor', watch:'İzle', showEveryone:'Herkese göster', viewOnly:'Sadece görüntüle', materialsUnavailable:'Materyaller henüz kullanılamıyor.', noMaterials:'Bu ders için henüz materyal yok.', pdfOpensOutside:'PDF sınıf dışında açılır', pdfPreviewBlocked:'Tarayıcı bu PDF önizlemesini engelliyor. Yeni sekmede açın.', openMaterialNewTab:'Bu materyali yeni sekmede aç', fileCannotPreview:'Bu dosya türü sınıf içinde önizlenemez.', openPdf:'PDF aç' },
    ru: { online:'онлайн', weakConnection:'слабое соединение', connectionStable:'Соединение выглядит стабильным', watch:'Смотреть', showEveryone:'Показать всем', viewOnly:'Только просмотр', materialsUnavailable:'Материалы пока недоступны.', noMaterials:'Материалов к этому уроку пока нет.', pdfOpensOutside:'PDF открывается вне класса', pdfPreviewBlocked:'Браузер блокирует просмотр этого PDF внутри урока, поэтому откройте его в новой вкладке.', openMaterialNewTab:'Откройте материал в новой вкладке', fileCannotPreview:'Этот тип файла нельзя надежно показать внутри класса.', openPdf:'Открыть PDF' },
    uk: { online:'онлайн', weakConnection:'слабке з’єднання', connectionStable:'З’єднання виглядає стабільним', watch:'Дивитися', showEveryone:'Показати всім', viewOnly:'Лише перегляд', materialsUnavailable:'Матеріали поки недоступні.', noMaterials:'Матеріалів для цього уроку поки немає.', pdfOpensOutside:'PDF відкривається поза класом', pdfPreviewBlocked:'Браузер блокує перегляд PDF. Відкрийте його в новій вкладці.', openMaterialNewTab:'Відкрити матеріал у новій вкладці', fileCannotPreview:'Цей тип файлу не можна переглянути в класі.', openPdf:'Відкрити PDF' },
    kk: { online:'онлайн', weakConnection:'әлсіз байланыс', connectionStable:'Байланыс тұрақты көрінеді', watch:'Көру', showEveryone:'Барлығына көрсету', viewOnly:'Тек көру', materialsUnavailable:'Материалдар әзірге қолжетімді емес.', noMaterials:'Бұл сабаққа материалдар әлі жоқ.', pdfOpensOutside:'PDF сыныптан тыс ашылады', pdfPreviewBlocked:'Браузер PDF алдын ала қарауын бұғаттайды. Жаңа қойындыда ашыңыз.', openMaterialNewTab:'Материалды жаңа қойындыда ашу', fileCannotPreview:'Бұл файл түрін сынып ішінде қарау мүмкін емес.', openPdf:'PDF ашу' },
    az: { online:'onlayn', weakConnection:'zəif bağlantı', connectionStable:'Bağlantı sabit görünür', watch:'Bax', showEveryone:'Hamıya göstər', viewOnly:'Yalnız baxış', materialsUnavailable:'Materiallar hələ əlçatan deyil.', noMaterials:'Bu dərs üçün hələ material yoxdur.', pdfOpensOutside:'PDF sinifdən kənarda açılır', pdfPreviewBlocked:'Brauzer PDF önbaxışını bloklayır. Yeni tabda açın.', openMaterialNewTab:'Materialı yeni tabda aç', fileCannotPreview:'Bu fayl növünü sinifdə önizləmək olmur.', openPdf:'PDF aç' },
    uz: { online:'onlayn', weakConnection:'zaif ulanish', connectionStable:'Ulanish barqaror ko‘rinadi', watch:'Ko‘rish', showEveryone:'Hammaga ko‘rsatish', viewOnly:'Faqat ko‘rish', materialsUnavailable:'Materiallar hozircha mavjud emas.', noMaterials:'Bu dars uchun hali materiallar yo‘q.', pdfOpensOutside:'PDF sinfdan tashqarida ochiladi', pdfPreviewBlocked:'Brauzer PDF ko‘rishni bloklaydi. Yangi oynada oching.', openMaterialNewTab:'Materialni yangi oynada ochish', fileCannotPreview:'Bu fayl turini sinf ichida ko‘rib bo‘lmaydi.', openPdf:'PDF ochish' },
    tg: { online:'онлайн', weakConnection:'пайвасти суст', connectionStable:'Пайваст устувор менамояд', watch:'Дидан', showEveryone:'Ба ҳама нишон додан', viewOnly:'Танҳо дидан', materialsUnavailable:'Маводҳо ҳоло дастрас нестанд.', noMaterials:'Барои ин дарс ҳоло мавод нест.', pdfOpensOutside:'PDF берун аз синф кушода мешавад', pdfPreviewBlocked:'Браузер пешнамоиши PDF-ро мебандад. Дар ҷадвали нав кушоед.', openMaterialNewTab:'Маводро дар ҷадвали нав кушоед', fileCannotPreview:'Ин навъи файл дар синф пешнамоиш намешавад.', openPdf:'PDF кушоед' },
    fa: { online:'آنلاین', weakConnection:'اتصال ضعیف', connectionStable:'اتصال پایدار به نظر می‌رسد', watch:'مشاهده', showEveryone:'نمایش به همه', viewOnly:'فقط مشاهده', materialsUnavailable:'مواد هنوز در دسترس نیستند.', noMaterials:'هنوز ماده‌ای برای این درس نیست.', pdfOpensOutside:'PDF بیرون از کلاس باز می‌شود', pdfPreviewBlocked:'مرورگر پیش‌نمایش PDF را مسدود می‌کند. در یک برگه جدید باز کنید.', openMaterialNewTab:'این ماده را در برگه جدید باز کنید', fileCannotPreview:'این نوع فایل داخل کلاس قابل پیش‌نمایش نیست.', openPdf:'باز کردن PDF' },
    ar: { online:'متصل', weakConnection:'اتصال ضعيف', connectionStable:'الاتصال يبدو مستقراً', watch:'مشاهدة', showEveryone:'عرض للجميع', viewOnly:'عرض فقط', materialsUnavailable:'المواد غير متاحة بعد.', noMaterials:'لا توجد مواد لهذا الدرس بعد.', pdfOpensOutside:'يفتح PDF خارج الفصل', pdfPreviewBlocked:'المتصفح يحظر معاينة PDF. افتحه في تبويب جديد.', openMaterialNewTab:'افتح هذه المادة في تبويب جديد', fileCannotPreview:'لا يمكن معاينة هذا النوع من الملفات داخل الفصل.', openPdf:'فتح PDF' },
    vi: { online:'trực tuyến', weakConnection:'kết nối yếu', connectionStable:'Kết nối có vẻ ổn định', watch:'Xem', showEveryone:'Hiển thị cho mọi người', viewOnly:'Chỉ xem', materialsUnavailable:'Tài liệu chưa khả dụng.', noMaterials:'Chưa có tài liệu cho bài học này.', pdfOpensOutside:'PDF mở ngoài lớp học', pdfPreviewBlocked:'Trình duyệt chặn xem trước PDF. Hãy mở trong tab mới.', openMaterialNewTab:'Mở tài liệu này trong tab mới', fileCannotPreview:'Không thể xem trước loại tệp này trong lớp học.', openPdf:'Mở PDF' },
    zh: { online:'在线', weakConnection:'连接较弱', connectionStable:'连接看起来稳定', watch:'查看', showEveryone:'显示给所有人', viewOnly:'仅查看', materialsUnavailable:'材料暂不可用。', noMaterials:'本课还没有材料。', pdfOpensOutside:'PDF 将在课堂外打开', pdfPreviewBlocked:'浏览器阻止此 PDF 预览。请在新标签页打开。', openMaterialNewTab:'在新标签页打开此材料', fileCannotPreview:'此文件类型无法在课堂内预览。', openPdf:'打开 PDF' },
    ja: { online:'オンライン', weakConnection:'接続が弱い', connectionStable:'接続は安定しています', watch:'見る', showEveryone:'全員に表示', viewOnly:'表示のみ', materialsUnavailable:'教材はまだ利用できません。', noMaterials:'このレッスンの教材はまだありません。', pdfOpensOutside:'PDF は教室の外で開きます', pdfPreviewBlocked:'ブラウザが PDF プレビューをブロックしています。新しいタブで開いてください。', openMaterialNewTab:'この教材を新しいタブで開く', fileCannotPreview:'このファイル形式は教室内でプレビューできません。', openPdf:'PDF を開く' },
    ko: { online:'온라인', weakConnection:'약한 연결', connectionStable:'연결이 안정적으로 보입니다', watch:'보기', showEveryone:'모두에게 보이기', viewOnly:'보기 전용', materialsUnavailable:'자료를 아직 사용할 수 없습니다.', noMaterials:'이 수업에는 아직 자료가 없습니다.', pdfOpensOutside:'PDF가 교실 밖에서 열립니다', pdfPreviewBlocked:'브라우저가 PDF 미리보기를 차단합니다. 새 탭에서 여세요.', openMaterialNewTab:'이 자료를 새 탭에서 열기', fileCannotPreview:'이 파일 형식은 교실 안에서 미리볼 수 없습니다.', openPdf:'PDF 열기' }
  };
  Object.entries(CLASSROOM_EXTRA).forEach(([code, terms]) => Object.assign(L[code] || (L[code] = {}), terms));

  const PHRASES = {
    'Home':'home','Media':'media','Videos':'media','Live':'live','Courses':'courses','Events':'events','Messages':'messages','Practice':'practice','Schedule':'schedule','Rankings':'rankings','Profile':'profile','Dashboard':'dashboard','Management':'management','Live Studio':'liveStudio','Notes':'notes','All':'all','Languages':'languages','Arts':'arts','School':'school','Search':'search','Notifications':'notifications','Upload':'upload','Publish':'publish','Title':'title','Language':'language','Level':'level','Language level':'level','Email':'email','Role':'role','Full name':'fullName','City':'city','Country':'country','Native language':'nativeLanguage','Bio':'bio','Website':'website','Save changes':'saveChanges','Saved ✓':'saved','Sign out':'signOut','Open':'open','Close':'close','Add':'add','+ Add':'add','Send':'send','Free':'free','Teacher':'teacher','Learner':'learner','Organizer':'organizer','Organization':'organization','Administrator':'admin','Participants':'participants','Chat':'chat','Materials':'materials','Microphone':'microphone','Camera':'camera','Cameras':'cameras','Screen':'screen','Reactions':'reactions','Leave':'leave','Exit':'leave','Raise hand':'raiseHand','Lower hand':'lowerHand','Duvela Classroom':'classroom','Group lesson':'groupLesson','Lesson':'lesson','Enter lesson':'enterLesson','Camera is off':'cameraOff','Camera off':'cameraOff','Mic off':'micOff','Browser':'browser','Internet':'internet','Speaker':'speaker','Waiting to enter':'waitingEntry','Mute all':'muteAll','Stop cameras':'stopCameras','Lower all hands':'lowerAllHands','Write a message...':'writeMessage','Write a message…':'writeMessage','Lesson materials':'lessonMaterials','Material':'material','Full screen':'fullScreen','Stop':'stop','Back to screen':'backToScreen','Copy link':'copyLink','Copied':'copied','Ready to join.':'readyToJoin','You can join, but check highlighted items.':'joinWithWarnings','Check device permissions before joining.':'checkPermissions','online':'online','weak connection':'weakConnection','Connection looks stable':'connectionStable','Watch':'watch','Show everyone':'showEveryone','View only':'viewOnly','Materials are not available yet.':'materialsUnavailable','No materials for this lesson yet.':'noMaterials','PDF opens outside the classroom':'pdfOpensOutside','Browsers block this PDF preview, so use a new tab for reliable viewing.':'pdfPreviewBlocked','Open this material in a new tab':'openMaterialNewTab','This file type cannot be previewed inside the classroom.':'fileCannotPreview','Open PDF':'openPdf',
    'Главная':'home','Медиа':'media','Эфиры':'live','Курсы':'courses','События':'events','Сообщения':'messages','Практика':'practice','Расписание':'schedule','Рейтинги':'rankings','Профиль':'profile','Участники':'participants','Материалы':'materials','Микрофон':'microphone','Камера':'camera','Камеры':'cameras','Экран':'screen','Реакции':'reactions','Выйти':'leave','Поднять руку':'raiseHand','Опустить руку':'lowerHand','Групповой урок':'groupLesson','Урок':'lesson','Камера выключена':'cameraOff','Браузер':'browser','Интернет':'internet','Динамик':'speaker','Ожидают входа':'waitingEntry','Материалы урока':'lessonMaterials','Во весь экран':'fullScreen','Остановить':'stop','Вернуться к экрану':'backToScreen'
  };

  function catalogLocales(localeCatalog) {
    const source = Array.isArray(localeCatalog?.locales) && localeCatalog.locales.length ? localeCatalog.locales : FALLBACK_LOCALES;
    return source.map((locale) => ({ code: String(locale.code || '').toLowerCase(), name: locale.name || String(locale.code || '').toUpperCase(), flag: locale.flag || '', dir: locale.dir || 'ltr' })).filter((locale) => locale.code);
  }

  function resolveLang(value, locales) {
    const raw = String(value || '').trim().toLowerCase();
    if (!raw) return 'en';
    if (locales.some((locale) => locale.code === raw)) return raw;
    const base = raw.split('-')[0];
    return locales.some((locale) => locale.code === base) ? base : 'en';
  }

  function catalogLookup(localeCatalog, lang, phrase) {
    if (!localeCatalog || !phrase || lang === 'en') return '';
    for (const bucket of ['base', 'extra']) {
      const english = localeCatalog[bucket]?.en || {};
      const selected = localeCatalog[bucket]?.[lang] || {};
      for (const [key, value] of Object.entries(english)) {
        if (value === phrase && selected[key]) return selected[key];
      }
    }
    return '';
  }

  function create(options = {}) {
    const localeCatalog = options.localeCatalog || global.DUVELA_WEB_I18N || null;
    const locales = catalogLocales(localeCatalog);
    const storageKeys = options.storageKeys || global.DuvelaWebConfig?.storageKeys || {};
    const configuredKey = storageKeys.lang || localeCatalog?.storageKey || 'duvela.webLang';
    const stored = options.lang || localStorage.getItem(configuredKey) || localStorage.getItem('duvela.web.lang') || navigator.language || 'en';
    const appLang = resolveLang(stored, locales);
    const locale = locales.find((item) => item.code === appLang) || locales[0] || FALLBACK_LOCALES[0];
    const intlLocale = LOCALE_TO_INTL[appLang] || appLang || 'en-US';
    const isRu = appLang === 'ru';

    function term(key) {
      return (L[appLang] && L[appLang][key]) || L.en[key] || key;
    }

    function translatePhrase(phrase) {
      const key = PHRASES[String(phrase || '')];
      if (key) return term(key);
      return catalogLookup(localeCatalog, appLang, phrase) || '';
    }

    function tr(en, ru) {
      if (appLang === 'en') return en;
      if (isRu && ru) return ru;
      return translatePhrase(en) || translatePhrase(ru) || en;
    }

    function applyDocument(target = document) {
      document.documentElement.lang = appLang;
      document.documentElement.dir = locale.dir || 'ltr';
      target.querySelectorAll('[data-i18n]').forEach((node) => {
        const key = node.getAttribute('data-i18n');
        if (key) node.textContent = term(key);
      });
      target.querySelectorAll('[data-i18n-placeholder]').forEach((node) => {
        const key = node.getAttribute('data-i18n-placeholder');
        if (key) node.setAttribute('placeholder', term(key));
      });
      target.querySelectorAll('[data-i18n-label]').forEach((node) => {
        const key = node.getAttribute('data-i18n-label');
        if (key) node.setAttribute('aria-label', term(key));
      });
    }

    return { appLang, isRu, locale, locales, intlLocale, tr, term, applyDocument, resolveLang: (value) => resolveLang(value, locales) };
  }

  global.DuvelaAppI18n = { create, locales: FALLBACK_LOCALES };
})(window);
